version: '3.8'

services:
  solana-monitor:
    build: .
    container_name: solana-security-monitor
    ports:
      - '3000:3000' # Backend API
      - '3001:3001' # Dashboard UI
    environment:
      - NODE_ENV=production
      - SOLANA_RPC_URL=${SOLANA_RPC_URL:-https://api.mainnet-beta.solana.com}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongo:27017/solana-monitor}
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: solana-monitor-db
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=solana-monitor
    restart: unless-stopped

volumes:
  mongo-data:
